### ISSUE TITLE
bunt#PlainTextLength does not return the correct size

### ISSUE THREAD

**Issue by lynxplay** [homeport/gonvenience#10]
Running the following unit test

```go
Expect(bunt.PlainTextLength("\x1b[0;32mINFO \x1b[mNo dependencies found")).To(BeEquivalentTo(len("INFO No dependencies found")))
```

one would expect the two values to be the same, as both the green color as well as the color reset should be ignored in the PlainTextLength method.

The unit test fails with "Expected 29 to be equivilant to 26". I personally didn't have the time nor energy to look into why that issue comes up so I don't have more insight on why it happens

**Comment by HeavyWombat** [comment]
Should be fixed by PR #11
